rabbitmq:
  host: localhost
  port: 5672
  username: adm_videos
  password: root

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: root
  schema: adm_videos
  url: localhost:${mysql.port}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration