spring:
  rabbitmq:
    admin:
      auto-create: true
    host: localhost
    port: 5672
    username: adm_videos
    password: root

mysql:
  username: root
  password: root
  schema: adm_videos
  url: localhost:3306

server:
  port: 8080
  servlet:
    context-path: /api
  undertow:
    threads:
      worker: 10
      io: 2